// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ContenidoAudioVisual struct {
	ID          string   `json:"id"`
	Nombre      string   `json:"nombre"`
	Descripcion *string  `json:"descripcion,omitempty"`
	Generos     []string `json:"generos"`
	TipoID      string   `json:"tipoId"`
	ImageURL    *string  `json:"imageUrl,omitempty"`
}

type ContenidoAudioVisualMapped struct {
	ID          string                    `json:"id"`
	Nombre      string                    `json:"nombre"`
	Descripcion *string                   `json:"descripcion,omitempty"`
	Generos     []*Genero                 `json:"generos"`
	Tipo        *TipoContenidoAudioVisual `json:"tipo"`
	ImageURL    *string                   `json:"imageUrl,omitempty"`
}

type Genero struct {
	ID     string `json:"id"`
	Nombre string `json:"nombre"`
}

type Mutation struct {
}

type NuevoContenidoAudioVisual struct {
	Nombre      string   `json:"nombre"`
	Descripcion string   `json:"descripcion"`
	Generos     []string `json:"generos"`
	TipoID      string   `json:"tipoId"`
	ImageURL    *string  `json:"imageUrl,omitempty"`
}

type Query struct {
}

type TipoContenidoAudioVisual struct {
	ID       string `json:"id"`
	Singular string `json:"singular"`
	Plural   string `json:"plural"`
}
